In [1]:
import numpy as np

In [13]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

##### input shape is (1,4)
##### weights shape is (3,4)
##### biases shape is (1,3)
##### output= (1,4)*(3,4).T  +(1,3)
##### output= (1,4)*(4,3)+(1,3)
##### output=(1,3)+(1,3)
##### output=(1,3)

In [14]:
inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)

In [16]:
layer_outputs=np.dot(inputs_array,weights_array.T)+biases_array
layer_outputs

array([4.8  , 1.21 , 2.385])

Note- To mutiply(np.dot()) A=vetor(1,4) to B=matrix(3,4). We can perform np.dot(A,B.T) OR np.dot(B,A). In second case numpy treat vector A as a matrix and convert it into column major(takes traspose). 

### Layers of neurons and batch of data

In [17]:
inputs = [[1.0, 2.0, 3.0, 2.5], 
          [2.0, 5.0, -1.0, 2.0], 
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

In [18]:
inputs_array=np.array(inputs)
weights_array_array=np.array(weights)
biases_array=np.array(biases)

In [19]:
layer_outputs=np.dot(inputs_array,weights_array.T)+biases_array
layer_outputs

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

### Two Layers of neurons and batch of data

In [21]:
inputs = [[1, 2, 3, 2.5],
          [2., 5., -1., 2],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

# Convert lists to numpy arrays
inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)
weights2_array = np.array(weights2)
biases2_array = np.array(biases2)

In [23]:
layer1_output=np.dot(inputs_array,weights_array.T)+biases_array
layer1_output

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [25]:
layer2_output=np.dot(layer1_output,weights2_array.T)+biases2
layer2_output

array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])